### ISSUE TITLE
How to implement this in my hexo blog?

### ISSUE THREAD

**Issue by Meraj-Kazi** [next-theme/hexo-generator-searchdb#12]
I'm new in hexo development. Created a site with hexo. Now trying to add a working search bar. How to implement yours? It would be nice of you to share some knowledge regarding this.

**Comment by stevenjoezhang** [comment]
I'm sorry for the late reply, I have created a front end script to proceed the search data generated by this plugin: https://github.com/next-theme/hexo-generator-searchdb/blob/main/dist/search.js

The documentation is updated: https://github.com/next-theme/hexo-generator-searchdb/commit/a37da5659f998bbdc5a4de5e5a02597e06b418fd
