### ISSUE TITLE
Archive theme-next/hexo-generator-searchdb

### ISSUE THREAD

**Issue by jiangtj** [next-theme/hexo-generator-searchdb#15]
I have archived theme-next/hexo-generator-searchdb, due to these two projects provide the same service, and published in the same package.

@stevenjoezhang If there are break changes, release the v2 version, consider compatibility with the theme-next (install v1)

https://github.com/theme-next/hexo-generator-searchdb

**Comment by stevenjoezhang** [comment]
OK, as of now, the plugin is backward compatible
