### ISSUE TITLE
generated search.xml is too large?

### ISSUE THREAD

**Issue by gamelife1314** [next-theme/hexo-generator-searchdb#22]
the search.xml is up to 2.6MB, how to reduce?

**Comment by stevenjoezhang** [comment]
This plugin is designed to work with no backend server, so all the post content will be added to the `search.xml`
You can use a third-party search service instead, e.g. Algolia: https://github.com/LouisBarranqueiro/hexo-algoliasearch

**Comment by gamelife1314** [comment]
ok

**Comment by gamelife1314** [comment]
能不能增加个选项，把文章中的代码过滤掉

**Comment by gamelife1314** [comment]
还可以进行分词，只保留有语义的内容，一些副词，主语什么的都可以去掉
