### ISSUE TITLE
无法搜索到最近发布的 post 内容

### ISSUE THREAD

**Issue by Maples7** [next-theme/hexo-generator-searchdb#29]
博客地址：https://maples7.com/
源码配置位置：
- _config.yml: https://github.com/Maples7/blog/blob/dd3fc871c72319e138b2b659a352fe1cc2d6c7b6/_config.yml#L122C1-L126C15
- _config.next.yml: https://github.com/Maples7/blog/blob/dd3fc871c72319e138b2b659a352fe1cc2d6c7b6/_config.next.yml#L739C1-L751C16

但是最近发现无法通过 local search 搜索到最近的发布文章内容。

比如：
搜索：热情
<img width="1890" alt="image" src="https://github.com/next-theme/hexo-generator-searchdb/assets/9960982/c1c7db68-9389-472e-a3f4-86c92c1410fe">
只能搜索到早期的几篇文章而无法搜索到最新的这篇博客：[热情、工作与理想主义｜为什么我要离开微软](https://maples7.com/2023/07/25/why-i-leave-microsoft/)

**Comment by stevenjoezhang** [comment]
<img width="998" alt="截屏2023-08-02 15 45 32" src="https://github.com/next-theme/hexo-generator-searchdb/assets/16272760/758964c6-17c3-4503-a752-ff86b276c2fc">

你的`search.xml`中包含非法字符（可能是文章中的不可见字符），因此搜索结果无法解析。你可以排查一下。

**Comment by Maples7** [comment]
@stevenjoezhang 非常感谢！已成功定位到问题点。
